#Each new term in the Fibonacci sequence 
#is generated by adding the previous two terms. 
#By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence
#whose values do not exceed four million, find the sum of the even-valued terms.


sum_even_fib = 0
anteprevious = 1
previous = 2

fib = previous
fibs_even = []
while fib < 4000000:
    if fib % 2 == 0:
        sum_even_fib += fib
        fibs_even.append(fib)
    fib = previous + anteprevious
    anteprevious = previous
    previous = fib

print("sum even: ", sum_even_fib)
print("#"*40)
print("fibs even: ", fibs_even)
print("#"*40)
print("#"*40)
print("sum even: ", sum_even_fib)
